glossary_terms = {
    "Ability Check",
    "Ability Score and Modifier",
    "Action",
    "Advantage",
    "Adventure",
    "Alignment",
    "Ally",
    "Area of Effect",
    "Armor Class",
    "Armor Training",
    "Attack",
    "Attack Roll",
    "Attitude",
    "Attunement",
    "Blinded",
    "Blindsight",
    "Bloodied",
    "Bonus Action",
    "Breaking Objects",
    "Bright Light",
    "Burning",
    "Burrow Speed",
    "Campaign",
    "Cantrip",
    "Carrying Capacity",
    "Challenge Rating",
    "Character Sheet",
    "Charmed",
    "Climb Speed",
    "Climbing",
    "Concentration",
    "Condition",
    "Cone",
    "Cover",
    "Crawling",
    "Creature",
    "Creature Type",
    "Critical Hit",
    "Cube",
    "Curses",
    "Cylinder",
    "D20 Test",
    "Damage",
    "Damage Roll",
    "Damage Threshold",
    "Damage Types",
    "Darkness",
    "Darkvision",
    "Dash",
    "Dead",
    "Deafened",
    "Death Saving Throw",
    "Dehydration",
    "Difficult Terrain",
    "Difficulty Class",
    "Dim Light",
    "Disadvantage",
    "Disengage",
    "Dodge",
    "Emanation",
    "Encounter",
    "Enemy",
    "Exhaustion",
    "Experience Points",
    "Expertise",
    "Falling",
    "Fly Speed",
    "Flying",
    "Friendly",
    "Frightened",
    "Grappled",
    "Grappling",
    "Hazard",
    "Healing",
    "Heavily Obscured",
    "Help",
    "Heroic Inspiration",
    "Hide",
    "High Jump",
    "Hit Point Dice",
    "Hit Points",
    "Hostile",
    "Hover",
    "Illusions",
    "Immunity",
    "Improvised Weapons",
    "Incapacitated",
    "Indifferent",
    "Influence",
    "Initiative",
    "Invisible",
    "Jumping",
    "Knocking Out a Creature",
    "Lightly Obscured",
    "Line",
    "Long Jump",
    "Long Rest",
    "Magic",
    "Magical Effect",
    "Malnutrition",
    "Monster",
    "Nonplayer Character",
    "Object",
    "Occupied Space",
    "Opportunity Attacks",
    "Paralyzed",
    "Passive Perception",
    "Per Day",
    "Petrified",
    "Player Character",
    "Poisoned",
    "Possession",
    "Proficiency",
    "Prone",
    "Reach",
    "Reaction",
    "Ready",
    "Resistance",
    "Restrained",
    "Ritual",
    "Round Down",
    "Rules Glossary",
    "Save",
    "Saving Throw",
    "Search",
    "Shape-Shifting",
    "Short Rest",
    "Simultaneous Effects",
    "Size",
    "Skill",
    "Speed",
    # "Spell",      # linked too many times and places
    "Spell Attack",
    "Spellcasting Focus",
    "Sphere",
    "Stable",
    "Stat Block",
    "Study",
    "Stunned",
    "Suffocation",
    "Surprise",
    "Swim Speed",
    "Swimming",
    "Target",
    "Telepathy",
    "Teleportation",
    "Temporary Hit Points",
    "Tremorsense",
    "Truesight",
    "Unarmed Strike",
    "Unconscious",
    "Unoccupied Space",
    "Utilize",
    "Vulnerability",
    "Weapon",
    "Weapon Attack",
}


def get_glossary_terms(profile=None):
    if profile == 'dnd51':
        return set()
    return glossary_terms
