magic_items = {
    "a": [
        "Adamantine Armor",
        "Ammunition, +1, +2, or +3",
        "Amulet of Health",
        "Amulet of Proof Against Detection and Location",
        "Amulet of the Planes",
        "Animated Shield",
        "Apparatus of the Crab",
        "Armor, +1, +2, or +3",
        "Armor of Invulnerability",
        "Armor of Resistance",
        "Armor of Vulnerability",
        "Arrow Catching Shield",
        "Arrow of Slaying",
    ],
    "b": [
        "Bag of Beans",
        "Bag of Devouring",
        "Bag of Holding",
        "Bag of Tricks",
        "Bead of Force",
        "Belt of Dwarvenkind",
        "Belt of Giant Strength",
        "Berserker Axe",
        "Boots of Elvenkind",
        "Boots of Levitation",
        "Boots of Speed",
        "Boots of Striding and Springing",
        "Boots of the Winterlands",
        "Bowl of Commanding Water Elementals",
        "Bracers of Archery",
        "Bracers of Defense",
        "Brazier of Commanding Fire Elementals",
        "Brooch of Shielding",
        "Broom of Flying",
    ],
    "c": [
        "Candle of Invocation",
        "Cape of the Mountebank",
        "Carpet of Flying",
        "Censer of Controlling Air Elementals",
        "Chime of Opening",
        "Circlet of Blasting",
        "Cloak of Arachnida",
        "Cloak of Displacement",
        "Cloak of Elvenkind",
        "Cloak of Protection",
        "Cloak of the Bat",
        "Cloak of the Manta Ray",
        "Crystal Ball",
        "Cube of Force",
        "Cubic Gate",
    ],
    "d": [
        "Dagger of Venom",
        "Dancing Sword",
        "Decanter of Endless Water",
        "Deck of Illusions",
        "Deck of Many Things",
        "Defender",
        "Demon Armor",
        "Dimensional Shackles",
        "Dragon Scale Mail",
        "Dragon Slayer",
        "Dust of Disappearance",
        "Dust of Dryness",
        "Dust of Sneezing and Choking",
        "Dwarven Plate",
        "Dwarven Thrower",
    ],
    "e": [
        "Efficient Quiver",
        "Efreeti Bottle",
        "Elemental Gem",
        "Elven Chain",
        "Eversmoking Bottle",
        "Eyes of Charming",
        "Eyes of Minute Seeing",
        "Eyes of the Eagle",
    ],
    "f": [
        "Feather Token",
        "Figurine of Wondrous Power",
        "Flame Tongue",
        "Folding Boat",
        "Frost Brand",
    ],
    "g": [
        "Gauntlets of Ogre Power",
        "Gem of Brightness",
        "Gem of Seeing",
        "Giant Slayer",
        "Glamoured Studded Leather",
        "Gloves of Missile Snaring",
        "Gloves of Swimming and Climbing",
        "Goggles of Night",
    ],
    "h": [
        "Hammer of Thunderbolts",
        "Handy Haversack",
        "Hat of Disguise",
        "Headband of Intellect",
        "Helm of Brilliance",
        "Helm of Comprehending Languages",
        "Helm of Telepathy",
        "Helm of Teleportation",
        "Holy Avenger",
        "Horn of Blasting",
        "Horn of Valhalla",
        "Horseshoes of a Zephyr",
        "Horseshoes of Speed",
    ],
    "i": [
        "Immovable Rod",
        "Instant Fortress",
        "Ioun Stone",
        "Iron Bands of Binding",
        "Iron Flask",
    ],
    "j": [
        "Javelin of Lightning",
    ],
    "l": [
        "Lantern of Revealing",
        "Luck Blade",
    ],
    "m": [
        "Mace of Disruption",
        "Mace of Smiting",
        "Mace of Terror",
        "Mantle of Spell Resistance",
        "Manual of Bodily Health",
        "Manual of Gainful Exercise",
        "Manual of Golems",
        "Manual of Quickness of Action",
        "Marvelous Pigments",
        "Medallion of Thoughts",
        "Mirror of Life Trapping",
        "Mithral Armor",
    ],
    "n": [
        "Necklace of Adaptation",
        "Necklace of Fireballs",
        "Necklace of Prayer Beads",
        "Nine Lives Stealer",
    ],
    "o": [
        "Oathbow",
        "Oil of Etherealness",
        "Oil of Sharpness",
        "Oil of Slipperiness",
        "Orb of Dragonkind",
    ],
    "p": [
        "Pearl of Power",
        "Periapt of Health",
        "Periapt of Proof Against Poison",
        "Periapt of Wound Closure",
        "Philter of Love",
        "Pipes of Haunting",
        "Pipes of the Sewers",
        "Plate Armor of Etherealness",
        "Portable Hole",
        "Potion of Animal Friendship",
        "Potion of Clairvoyance",
        "Potion of Climbing",
        "Potion of Diminution",
        "Potion of Flying",
        "Potion of Gaseous Form",
        "Potion of Giant Strength",
        "Potion of Growth",
        "Potion of Healing",
        "Potion of Heroism",
        "Potion of Invisibility",
        "Potion of Mind Reading",
        "Potion of Poison",
        "Potion of Resistance",
        "Potion of Speed",
        "Potion of Water Breathing",
    ],
    "r": [
        "Restorative Ointment",
        "Ring of Animal Influence",
        "Ring of Djinni Summoning",
        "Ring of Elemental Command",
        "Ring of Evasion",
        "Ring of Feather Falling",
        "Ring of Free Action",
        "Ring of Invisibility",
        "Ring of Jumping",
        "Ring of Mind Shielding",
        "Ring of Protection",
        "Ring of Regeneration",
        "Ring of Resistance",
        "Ring of Shooting Stars",
        "Ring of Spell Storing",
        "Ring of Spell Turning",
        "Ring of Swimming",
        "Ring of Telekinesis",
        "Ring of the Ram",
        "Ring of Three Wishes",
        "Ring of Warmth",
        "Ring of Water Walking",
        "Ring of X Ray Vision",
        "Robe of Eyes",
        "Robe of Scintillating Colors",
        "Robe of Stars",
        "Robe of the Archmagi",
        "Robe of Useful Items",
        "Rod of Absorption",
        "Rod of Alertness",
        "Rod of Lordly Might",
        "Rod of Rulership",
        "Rod of Security",
        "Rope of Climbing",
        "Rope of Entanglement",
    ],
    "s": [
        "Scarab of Protection",
        "Scimitar of Speed",
        "Shield, +1, +2, or +3",
        "Shield of Missile Attraction",
        "Slippers of Spider Climbing",
        "Sovereign Glue",
        "Spell Scroll",
        "Spellguard Shield",
        "Sphere of Annihilation",
        "Staff of Charming",
        "Staff of Fire",
        "Staff of Frost",
        "Staff of Healing",
        "Staff of Power",
        "Staff of Striking",
        "Staff of Swarming Insects",
        "Staff of the Magi",
        "Staff of the Python",
        "Staff of the Woodlands",
        "Staff of Thunder and Lightning",
        "Staff of Withering",
        "Stone of Controlling Earth Elementals",
        "Stone of Good Luck",
        "Sun Blade",
        "Sword of Life Stealing",
        "Sword of Sharpness",
        "Sword of Wounding",
    ],
    "t": [
        "Talisman of Pure Good",
        "Talisman of the Sphere",
        "Talisman of Ultimate Evil",
        "Tome of Clear Thought",
        "Tome of Leadership and Influence",
        "Tome of Understanding",
        "Trident of Fish Command",
    ],
    "u": [
        "Universal Solvent",
    ],
    "v": [
        "Vicious Weapon",
        "Vorpal Sword",
    ],
    "w": [
        "Wand of Binding",
        "Wand of Enemy Detection",
        "Wand of Fear",
        "Wand of Fireballs",
        "Wand of Lightning Bolts",
        "Wand of Magic Detection",
        "Wand of Magic Missiles",
        "Wand of Paralysis",
        "Wand of Polymorph",
        "Wand of Secrets",
        "Wand of the War Mage",
        "Wand of Web",
        "Wand of Wonder",
        "Weapon, +1, +2, or +3",
        "Well of Many Worlds",
        "Wind Fan",
        "Winged Boots",
        "Wings of Flying",
    ],
}
