monsters = {
    'a': [
        "Aboleth",
        "Adult Black Dragon",
        "Adult Blue Dragon",
        "Adult Brass Dragon",
        "Adult Bronze Dragon",
        "Adult Copper Dragon",
        "Adult Gold Dragon",
        "Adult Green Dragon",
        "Adult Red Dragon",
        "Adult Silver Dragon",
        "Adult White Dragon",
        "Air Elemental",
        "Allosaurus",
        "Ancient Black Dragon",
        "Ancient Blue Dragon",
        "Ancient Brass Dragon",
        "Ancient Bronze Dragon",
        "Ancient Copper Dragon",
        "Ancient Gold Dragon",
        "Ancient Green Dragon",
        "Ancient Red Dragon",
        "Ancient Silver Dragon",
        "Ancient White Dragon",
        "Animated Armor",
        "Animated Flying Sword",
        "Animated Rug of Smothering",
        "Ankheg",
        "Ankylosaurus",
        "Ape",
        "Archelon",
        "Archmage",
        "Assassin",
        "Awakened Shrub",
        "Awakened Tree",
        "Axe Beak",
        "Azer Sentinel",
    ],
    'b': [
        "Baboon",
        "Badger",
        "Balor",
        "Bandit",
        "Bandit Captain",
        "Barbed Devil",
        "Basilisk",
        "Bat",
        "Bearded Devil",
        "Behir",
        "Berserker",
        "Black Bear",
        "Black Dragon Wyrmling",
        "Black Pudding",
        "Blink Dog",
        "Blood Hawk",
        "Blue Dragon Wyrmling",
        "Boar",
        "Bone Devil",
        "Brass Dragon Wyrmling",
        "Bronze Dragon Wyrmling",
        "Brown Bear",
        "Bugbear Stalker",
        "Bugbear Warrior",
        "Bulette",
    ],
    'c': [
        "Camel",
        "Cat",
        "Centaur Trooper",
        "Chain Devil",
        "Chimera",
        "Chuul",
        "Clay Golem",
        "Cloaker",
        "Cloud Giant",
        "Cockatrice",
        "Commoner",
        "Constrictor Snake",
        "Copper Dragon Wyrmling",
        "Couatl",
        "Crab",
        "Crocodile",
        "Cultist",
        "Cultist Fanatic",
    ],
    'd': [
        "Darkmantle",
        "Death Dog",
        "Deer",
        "Deva",
        "Dire Wolf",
        "Djinni",
        "Doppelganger",
        "Draft Horse",
        "Dragon Turtle",
        "Dretch",
        "Drider",
        "Druid",
        "Dryad",
        "Dust Mephit",
    ],
    'e': [
        "Eagle",
        "Earth Elemental",
        "Efreeti",
        "Elephant",
        "Elk",
        "Erinyes",
        "Ettercap",
        "Ettin",
    ],
    'f': [
        "Fire Elemental",
        "Fire Giant",
        "Flesh Golem",
        "Flying Snake",
        "Frog",
        "Frost Giant",
    ],
    'g': [
        "Gargoyle",
        "Gelatinous Cube",
        "Ghast",
        "Ghost",
        "Ghoul",
        "Giant Ape",
        "Giant Badger",
        "Giant Bat",
        "Giant Boar",
        "Giant Centipede",
        "Giant Constrictor Snake",
        "Giant Crab",
        "Giant Crocodile",
        "Giant Eagle",
        "Giant Elk",
        "Giant Fire Beetle",
        "Giant Frog",
        "Giant Goat",
        "Giant Hyena",
        "Giant Lizard",
        "Giant Octopus",
        "Giant Owl",
        "Giant Rat",
        "Giant Scorpion",
        "Giant Seahorse",
        "Giant Shark",
        "Giant Spider",
        "Giant Toad",
        "Giant Venomous Snake",
        "Giant Vulture",
        "Giant Wasp",
        "Giant Weasel",
        "Giant Wolf Spider",
        "Gibbering Mouther",
        "Glabrezu",
        "Gladiator",
        "Gnoll Warrior",
        "Goat",
        "Goblin Boss",
        "Goblin Minion",
        "Goblin Warrior",
        "Gold Dragon Wyrmling",
        "Gorgon",
        "Gray Ooze",
        "Green Dragon Wyrmling",
        "Green Hag",
        "Grick",
        "Griffon",
        "Grimlock",
        "Guard",
        "Guard Captain",
        "Guardian Naga",
    ],
    'h': [
        "Half-Dragon",
        "Harpy",
        "Hawk",
        "Hell Hound",
        "Hezrou",
        "Hill Giant",
        "Hippogriff",
        "Hippopotamus",
        "Hobgoblin Captain",
        "Hobgoblin Warrior",
        "Homunculus",
        "Horned Devil",
        "Hunter Shark",
        "Hydra",
        "Hyena",
    ],
    'i': [
        "Ice Devil",
        "Ice Mephit",
        "Imp",
        "Incubus",
        "Invisible Stalker",
        "Iron Golem",
    ],
    'j': [
        "Jackal",
    ],
    'k': [
        "Killer Whale",
        "Knight",
        "Kobold Warrior",
        "Kraken",
    ],
    'l': [
        "Lamia",
        "Lemure",
        "Lich",
        "Lion",
        "Lizard",
    ],
    'm': [
        "Mage",
        "Magma Mephit",
        "Magmin",
        "Mammoth",
        "Manticore",
        "Marilith",
        "Mastiff",
        "Medusa",
        "Merfolk Skirmisher",
        "Merrow",
        "Mimic",
        "Minotaur Skeleton",
        "Minotaur of Baphomet",
        "Mule",
        "Mummy",
        "Mummy Lord",
    ],
    'n': [
        "Nalfeshnee",
        "Night Hag",
        "Nightmare",
        "Noble",
    ],
    'o': [
        "Ochre Jelly",
        "Octopus",
        "Ogre",
        "Ogre Zombie",
        "Oni",
        "Otyugh",
        "Owl",
        "Owlbear",
    ],
    'p': [
        "Panther",
        "Pegasus",
        "Phase Spider",
        "Piranha",
        "Pirate",
        "Pirate Captain",
        "Pit Fiend",
        "Planetar",
        "Plesiosaurus",
        "Polar Bear",
        "Pony",
        "Priest",
        "Priest Acolyte",
        "Pseudodragon",
        "Pteranodon",
        "Purple Worm",
    ],
    'q': [
        "Quasit",
    ],
    'r': [
        "Rakshasa",
        "Rat",
        "Raven",
        "Red Dragon Wyrmling",
        "Reef Shark",
        "Remorhaz",
        "Rhinoceros",
        "Riding Horse",
        "Roc",
        "Roper",
        "Rust Monster",
    ],
    's': [
        "Saber-Toothed Tiger",
        "Sahuagin Warrior",
        "Salamander",
        "Satyr",
        "Scorpion",
        "Scout",
        "Sea Hag",
        "Seahorse",
        "Shadow",
        "Shambling Mound",
        "Shield Guardian",
        "Shrieker Fungus",
        "Silver Dragon Wyrmling",
        "Skeleton",
        "Solar",
        "Specter",
        "Sphinx of Lore",
        "Sphinx of Valor",
        "Sphinx of Wonder",
        "Spider",
        "Spirit Naga",
        "Sprite",
        "Spy",
        "Steam Mephit",
        "Stirge",
        "Stone Giant",
        "Stone Golem",
        "Storm Giant",
        "Succubus",
        "Swarm of Bats",
        "Swarm of Crawling Claws",
        "Swarm of Insects",
        "Swarm of Piranhas",
        "Swarm of Rats",
        "Swarm of Ravens",
        "Swarm of Venomous Snakes",
    ],
    't': [
        "Tarrasque",
        "Tiger",
        "Tough",
        "Tough Boss",
        "Treant",
        "Triceratops",
        "Troll",
        "Troll Limb",
        "Tyrannosaurus Rex",
    ],
    'u': [
        "Unicorn",
    ],
    'v': [
        "Vampire",
        "Vampire Familiar",
        "Vampire Spawn",
        "Venomous Snake",
        "Violet Fungus",
        "Vrock",
        "Vulture",
    ],
    'w': [
        "Warhorse",
        "Warhorse Skeleton",
        "Warrior Infantry",
        "Warrior Veteran",
        "Water Elemental",
        "Weasel",
        "Werebear",
        "Wereboar",
        "Wererat",
        "Weretiger",
        "Werewolf",
        "White Dragon Wyrmling",
        "Wight",
        "Will-o'-Wisp",
        "Winter Wolf",
        "Wolf",
        "Worg",
        "Wraith",
        "Wyvern",
    ],
    'x': [
        "Xorn",
    ],
    'y': [
        "Young Black Dragon",
        "Young Blue Dragon",
        "Young Brass Dragon",
        "Young Bronze Dragon",
        "Young Copper Dragon",
        "Young Gold Dragon",
        "Young Green Dragon",
        "Young Red Dragon",
        "Young Silver Dragon",
        "Young White Dragon",
    ],
    'z': [
        "Zombie",
    ],
}
