common_spells = {
    'a': [
        "Acid Arrow",
        "Acid Splash",
        "Aid",
        "Alarm",
        "Alter Self",
        "Animal Friendship",
        "Animal Messenger",
        "Animal Shapes",
        "Animate Dead",
        "Animate Objects",
        "Antilife Shell",
        "Antimagic Field",
        "Antipathy/Sympathy",
        "Arcane Eye",
        "Arcane Hand",
        "Arcane Lock",
        "Arcane Sword",
        "Arcanist's Magic Aura",
        "Astral Projection",
        "Augury",
        "Awaken",
    ],
    'b': [
        "Bane",
        "Banishment",
        "Barkskin",
        "Beacon of Hope",
        "Bestow Curse",
        "Black Tentacles",
        "Blade Barrier",
        "Bless",
        "Blight",
        "Blindness/Deafness",
        "Blink",
        "Blur",
        "Burning Hands",
    ],
    'c': [
        "Call Lightning",
        "Calm Emotions",
        "Chain Lightning",
        "Charm Monster",
        "Charm Person",
        "Chill Touch",
        "Circle of Death",
        "Clairvoyance",
        "Clone",
        "Cloudkill",
        "Color Spray",
        "Command",
        "Commune",
        "Commune with Nature",
        "Comprehend Languages",
        "Compulsion",
        "Cone of Cold",
        "Confusion",
        "Conjure Animals",
        "Conjure Celestial",
        "Conjure Elemental",
        "Conjure Fey",
        "Conjure Minor Elementals",
        "Conjure Woodland Beings",
        "Contact Other Plane",
        "Contagion",
        "Contingency",
        "Continual Flame",
        "Control Water",
        "Control Weather",
        "Counterspell",
        "Create Food and Water",
        "Create or Destroy Water",
        "Create Undead",
        "Creation",
        "Cure Wounds",
    ],
    'd': [
        "Dancing Lights",
        "Darkness",
        "Darkvision",
        "Daylight",
        "Death Ward",
        "Delayed Blast Fireball",
        "Demiplane",
        "Detect Evil and Good",
        "Detect Magic",
        "Detect Poison and Disease",
        "Detect Thoughts",
        "Dimension Door",
        "Disguise Self",
        "Disintegrate",
        "Dispel Evil and Good",
        "Dispel Magic",
        "Dissonant Whispers",
        "Divination",
        "Divine Favor",
        "Divine Word",
        "Dominate Beast",
        "Dominate Monster",
        "Dominate Person",
        "Dream",
        "Druidcraft",
    ],
    'e': [
        "Earthquake",
        "Eldritch Blast",
        "Enhance Ability",
        "Enlarge/Reduce",
        "Entangle",
        "Enthrall",
        "Etherealness",
        "Expeditious Retreat",
        "Eyebite",
    ],
    'f': [
        "Fabricate",
        "Faerie Fire",
        "Faithful Hound",
        "False Life",
        "Fear",
        "Feather Fall",
        "Find Familiar",
        "Find Steed",
        "Find the Path",
        "Find Traps",
        "Finger of Death",
        "Fire Bolt",
        "Fire Shield",
        "Fire Storm",
        "Fireball",
        "Flame Blade",
        "Flame Strike",
        "Flaming Sphere",
        "Flesh to Stone",
        "Floating Disk",
        "Fly",
        "Fog Cloud",
        "Forbiddance",
        "Forcecage",
        "Foresight",
        "Freedom of Movement",
        "Freezing Sphere",
    ],
    'g': [
        "Gaseous Form",
        "Gate",
        "Geas",
        "Gentle Repose",
        "Giant Insect",
        "Glibness",
        "Globe of Invulnerability",
        "Glyph of Warding",
        "Goodberry",
        "Grease",
        "Greater Invisibility",
        "Greater Restoration",
        "Guardian of Faith",
        "Guards and Wards",
        "Guidance",
        "Guiding Bolt",
        "Gust of Wind",
    ],
    'h': [
        "Hallow",
        "Hallucinatory Terrain",
        "Harm",
        "Haste",
        "Heal",
        "Healing Word",
        "Heat Metal",
        "Hellish Rebuke",
        "Heroes' Feast",
        "Heroism",
        "Hideous Laughter",
        "Hold Monster",
        "Hold Person",
        "Holy Aura",
        "Hunter's Mark",
        "Hypnotic Pattern",
    ],
    'i': [
        "Ice Storm",
        "Identify",
        "Illusory Script",
        "Imprisonment",
        "Incendiary Cloud",
        "Inflict Wounds",
        "Insect Plague",
        "Instant Summons",
        "Invisibility",
        "Irresistible Dance",
    ],
    'j': [
        "Jump",
    ],
    'k': [
        "Knock",
    ],
    'l': [
        "Legend Lore",
        "Lesser Restoration",
        "Levitate",
        "Light",
        "Lightning Bolt",
        "Locate Animals or Plants",
        "Locate Creature",
        "Locate Object",
        "Longstrider",
    ],
    'm': [
        "Mage Armor",
        "Mage Hand",
        "Magic Circle",
        "Magic Jar",
        "Magic Missile",
        "Magic Mouth",
        "Magic Weapon",
        "Magnificent Mansion",
        "Major Image",
        "Mass Cure Wounds",
        "Mass Heal",
        "Mass Healing Word",
        "Mass Suggestion",
        "Maze",
        "Meld into Stone",
        "Mending",
        "Message",
        "Meteor Swarm",
        "Mind Blank",
        "Minor Illusion",
        "Mirage Arcane",
        "Mirror Image",
        "Mislead",
        "Misty Step",
        "Modify Memory",
        "Moonbeam",
        "Move Earth",
    ],
    'n': [
        "Nondetection",
    ],
    'p': [
        "Pass without Trace",
        "Passwall",
        "Phantasmal Killer",
        "Phantom Steed",
        "Planar Ally",
        "Planar Binding",
        "Plane Shift",
        "Plant Growth",
        "Poison Spray",
        "Polymorph",
        "Power Word Kill",
        "Power Word Stun",
        "Prayer of Healing",
        "Prestidigitation",
        "Prismatic Spray",
        "Prismatic Wall",
        "Private Sanctum",
        "Produce Flame",
        "Programmed Illusion",
        "Project Image",
        "Protection from Energy",
        "Protection from Evil and Good",
        "Protection from Poison",
        "Purify Food and Drink",
    ],
    'r': [
        "Raise Dead",
        "Ray of Enfeeblement",
        "Ray of Frost",
        "Regenerate",
        "Reincarnate",
        "Remove Curse",
        "Resilient Sphere",
        "Resistance",
        "Resurrection",
        "Reverse Gravity",
        "Revivify",
        "Rope Trick",
    ],
    's': [
        "Sacred Flame",
        "Sanctuary",
        "Scorching Ray",
        "Scrying",
        "Secret Chest",
        "See Invisibility",
        "Seeming",
        "Sending",
        "Sequester",
        "Shapechange",
        "Shatter",
        "Shield",
        "Shield of Faith",
        "Shillelagh",
        "Shocking Grasp",
        "Silence",
        "Silent Image",
        "Simulacrum",
        "Sleep",
        "Sleet Storm",
        "Slow",
        "Spare the Dying",
        "Speak with Animals",
        "Speak with Dead",
        "Speak with Plants",
        "Spider Climb",
        "Spike Growth",
        "Spirit Guardians",
        "Spiritual Weapon",
        "Starry Wisp",
        "Stinking Cloud",
        "Stone Shape",
        "Stoneskin",
        "Storm of Vengeance",
        "Suggestion",
        "Sunbeam",
        "Sunburst",
        "Symbol",
    ],
    't': [
        "Telekinesis",
        "Telepathic Bond",
        "Teleport",
        "Teleportation Circle",
        "Thaumaturgy",
        "Thunderwave",
        "Time Stop",
        "Tiny Hut",
        "Tongues",
        "Transport via Plants",
        "Tree Stride",
        "True Polymorph",
        "True Resurrection",
        "True Seeing",
        "True Strike",
    ],
    'u': [
        "Unseen Servant",
    ],
    'v': [
        "Vampiric Touch",
        "Vicious Mockery",
    ],
    'w': [
        "Wall of Fire",
        "Wall of Force",
        "Wall of Ice",
        "Wall of Stone",
        "Wall of Thorns",
        "Warding Bond",
        "Water Breathing",
        "Water Walk",
        "Web",
        "Weird",
        "Wind Walk",
        "Wind Wall",
        "Wish",
        "Word of Recall",
    ],
    'z': [
        "Zone of Truth",
    ],
}

dnd51_spells = {
    'b': [
        "Branding Smite",
    ],
    'f': [
        "Feeblemind",
    ],
}

dnd521_spells = {
    'a': [
        "Aura of Life",
    ],
    'b': [
        "Befuddlement",
    ],
    'c': [
        "Chromatic Orb",
    ],
    'd': [
        "Divine Smite",
        "Dragon's Breath",
    ],
    'e': [
        "Elementalism",
        "Ensnaring Strike",
    ],
    'h': [
        "Hex",
    ],
    'i': [
        "Ice Knife",
    ],
    'm': [
        "Mind Spike",
    ],
    'p': [
        "Phantasmal Force",
        "Power Word Heal",
    ],
    'r': [
        "Ray of Sickness",
    ],
    's': [
        "Searing Smite",
        "Shining Smite",
        "Sorcerous Burst",
        "Summon Dragon",
    ],
    't': [
        "Tsunami",
    ],
    'v': [
        "Vitriolic Sphere",
    ],
}


def get_spell_list(version='dnd521'):
    result = {}
    for letter in 'abcdefghijklmnopqrstuvwxyz':
        result[letter] = []
        if letter in common_spells:
            result[letter].extend(common_spells[letter])
        if version == 'dnd51' and letter in dnd51_spells:
            result[letter].extend(dnd51_spells[letter])
        if version == 'dnd521' and letter in dnd521_spells:
            result[letter].extend(dnd521_spells[letter])
        if result[letter]:
            result[letter].sort()
    return {k: v for k, v in result.items() if v}


def get_next_unemphasised_spell(spell_list):
    import re
    all_spells = []
    for spells in spell_list.values():
        all_spells.extend(spells)
    sorted_spells = sorted(all_spells, key=len, reverse=True)
    escaped_spells = [re.escape(spell) for spell in sorted_spells]
    pattern = r'(?<!\*)(' + '|'.join(escaped_spells) + r')(?!\*)'
    return re.compile(pattern)


spells = get_spell_list('dnd521')
