name: Zip Obsidian vault

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-vault:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install tabulate
      run: |
        pip install tabulate

    - name: Create zip
      run: |
        make vaults

    - name: Upload 51 zip
      uses: actions/upload-artifact@v4
      with:
        name: dnd_51_srd
        path: /tmp/dnd_51_srd.zip
        
    - name: Upload 521 zip
      uses: actions/upload-artifact@v4
      with:
        name: dnd_521_srd
        path: /tmp/dnd_521_srd.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          /tmp/dnd_51_srd.zip
          /tmp/dnd_521_srd.zip
